package testmaker.dao;

import testmaker.entity.KnowledgePoint;

public interface KnowledgePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbggenerated
     */
    int insert(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbggenerated
     */
    KnowledgePoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgePoint record);
}