package testmaker.dao;

import testmaker.entity.QuestionLanguage;

import java.util.List;

public interface QuestionLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_language
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_language
     *
     * @mbggenerated
     */
    int insert(QuestionLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_language
     *
     * @mbggenerated
     */
    int insertSelective(QuestionLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_language
     *
     * @mbggenerated
     */
    QuestionLanguage selectByPrimaryKey(Integer id);

    List<QuestionLanguage> selectLanguages();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_language
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_language
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionLanguage record);
}