package testmaker.dao;

import testmaker.entity.QuestionChoice;

public interface QuestionChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    int insert(QuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    int insertSelective(QuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    QuestionChoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(QuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_choice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionChoice record);
}