package testmaker.dao;

import testmaker.entity.QuestionImage;

public interface QuestionImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_image
     *
     * @mbggenerated
     */
    int insert(QuestionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_image
     *
     * @mbggenerated
     */
    int insertSelective(QuestionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_image
     *
     * @mbggenerated
     */
    QuestionImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionImage record);
}