package testmaker.entity;

import java.util.Date;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.created_on
     *
     * @mbggenerated
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.updated_on
     *
     * @mbggenerated
     */
    private Date updatedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.syllabus_id
     *
     * @mbggenerated
     */
    private Integer syllabusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.id
     *
     * @return the value of chapter.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.id
     *
     * @param id the value for chapter.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.created_on
     *
     * @return the value of chapter.created_on
     *
     * @mbggenerated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.created_on
     *
     * @param createdOn the value for chapter.created_on
     *
     * @mbggenerated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.updated_on
     *
     * @return the value of chapter.updated_on
     *
     * @mbggenerated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.updated_on
     *
     * @param updatedOn the value for chapter.updated_on
     *
     * @mbggenerated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.number
     *
     * @return the value of chapter.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.number
     *
     * @param number the value for chapter.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.title
     *
     * @return the value of chapter.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.title
     *
     * @param title the value for chapter.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.syllabus_id
     *
     * @return the value of chapter.syllabus_id
     *
     * @mbggenerated
     */
    public Integer getSyllabusId() {
        return syllabusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.syllabus_id
     *
     * @param syllabusId the value for chapter.syllabus_id
     *
     * @mbggenerated
     */
    public void setSyllabusId(Integer syllabusId) {
        this.syllabusId = syllabusId;
    }
}