package testmaker.entity;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.created_on
     *
     * @mbggenerated
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.updated_on
     *
     * @mbggenerated
     */
    private Date updatedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.custom_field1
     *
     * @mbggenerated
     */
    private String customField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.custom_field2
     *
     * @mbggenerated
     */
    private String customField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.custom_field3
     *
     * @mbggenerated
     */
    private String customField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.exported_on
     *
     * @mbggenerated
     */
    private Date exportedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.finish_date
     *
     * @mbggenerated
     */
    private Date finishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.exported_by
     *
     * @mbggenerated
     */
    private Integer exportedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.facilitator_id
     *
     * @mbggenerated
     */
    private Integer facilitatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.syllabus_id
     *
     * @mbggenerated
     */
    private Integer syllabusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.created_on
     *
     * @return the value of project.created_on
     *
     * @mbggenerated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.created_on
     *
     * @param createdOn the value for project.created_on
     *
     * @mbggenerated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.updated_on
     *
     * @return the value of project.updated_on
     *
     * @mbggenerated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.updated_on
     *
     * @param updatedOn the value for project.updated_on
     *
     * @mbggenerated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.custom_field1
     *
     * @return the value of project.custom_field1
     *
     * @mbggenerated
     */
    public String getCustomField1() {
        return customField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.custom_field1
     *
     * @param customField1 the value for project.custom_field1
     *
     * @mbggenerated
     */
    public void setCustomField1(String customField1) {
        this.customField1 = customField1 == null ? null : customField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.custom_field2
     *
     * @return the value of project.custom_field2
     *
     * @mbggenerated
     */
    public String getCustomField2() {
        return customField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.custom_field2
     *
     * @param customField2 the value for project.custom_field2
     *
     * @mbggenerated
     */
    public void setCustomField2(String customField2) {
        this.customField2 = customField2 == null ? null : customField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.custom_field3
     *
     * @return the value of project.custom_field3
     *
     * @mbggenerated
     */
    public String getCustomField3() {
        return customField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.custom_field3
     *
     * @param customField3 the value for project.custom_field3
     *
     * @mbggenerated
     */
    public void setCustomField3(String customField3) {
        this.customField3 = customField3 == null ? null : customField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.exported_on
     *
     * @return the value of project.exported_on
     *
     * @mbggenerated
     */
    public Date getExportedOn() {
        return exportedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.exported_on
     *
     * @param exportedOn the value for project.exported_on
     *
     * @mbggenerated
     */
    public void setExportedOn(Date exportedOn) {
        this.exportedOn = exportedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.finish_date
     *
     * @return the value of project.finish_date
     *
     * @mbggenerated
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.finish_date
     *
     * @param finishDate the value for project.finish_date
     *
     * @mbggenerated
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.start_date
     *
     * @return the value of project.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.start_date
     *
     * @param startDate the value for project.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.exported_by
     *
     * @return the value of project.exported_by
     *
     * @mbggenerated
     */
    public Integer getExportedBy() {
        return exportedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.exported_by
     *
     * @param exportedBy the value for project.exported_by
     *
     * @mbggenerated
     */
    public void setExportedBy(Integer exportedBy) {
        this.exportedBy = exportedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.facilitator_id
     *
     * @return the value of project.facilitator_id
     *
     * @mbggenerated
     */
    public Integer getFacilitatorId() {
        return facilitatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.facilitator_id
     *
     * @param facilitatorId the value for project.facilitator_id
     *
     * @mbggenerated
     */
    public void setFacilitatorId(Integer facilitatorId) {
        this.facilitatorId = facilitatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status_id
     *
     * @return the value of project.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status_id
     *
     * @param statusId the value for project.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.syllabus_id
     *
     * @return the value of project.syllabus_id
     *
     * @mbggenerated
     */
    public Integer getSyllabusId() {
        return syllabusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.syllabus_id
     *
     * @param syllabusId the value for project.syllabus_id
     *
     * @mbggenerated
     */
    public void setSyllabusId(Integer syllabusId) {
        this.syllabusId = syllabusId;
    }
}