package testmaker.entity;

public class QuestionWithBLOBs extends Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.scenario
     *
     * @mbggenerated
     */
    private String scenario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.stem
     *
     * @mbggenerated
     */
    private String stem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.scenario
     *
     * @return the value of question.scenario
     *
     * @mbggenerated
     */
    public String getScenario() {
        return scenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.scenario
     *
     * @param scenario the value for question.scenario
     *
     * @mbggenerated
     */
    public void setScenario(String scenario) {
        this.scenario = scenario == null ? null : scenario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.stem
     *
     * @return the value of question.stem
     *
     * @mbggenerated
     */
    public String getStem() {
        return stem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.stem
     *
     * @param stem the value for question.stem
     *
     * @mbggenerated
     */
    public void setStem(String stem) {
        this.stem = stem == null ? null : stem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.remark
     *
     * @return the value of question.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.remark
     *
     * @param remark the value for question.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}