package testmaker.entity;

import java.util.Date;

public class QuestionChoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.created_on
     *
     * @mbggenerated
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.updated_on
     *
     * @mbggenerated
     */
    private Date updatedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.choice_label
     *
     * @mbggenerated
     */
    private String choiceLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.is_correct_answer
     *
     * @mbggenerated
     */
    private Boolean isCorrectAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_choice.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.id
     *
     * @return the value of question_choice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.id
     *
     * @param id the value for question_choice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.created_on
     *
     * @return the value of question_choice.created_on
     *
     * @mbggenerated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.created_on
     *
     * @param createdOn the value for question_choice.created_on
     *
     * @mbggenerated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.updated_on
     *
     * @return the value of question_choice.updated_on
     *
     * @mbggenerated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.updated_on
     *
     * @param updatedOn the value for question_choice.updated_on
     *
     * @mbggenerated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.choice_label
     *
     * @return the value of question_choice.choice_label
     *
     * @mbggenerated
     */
    public String getChoiceLabel() {
        return choiceLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.choice_label
     *
     * @param choiceLabel the value for question_choice.choice_label
     *
     * @mbggenerated
     */
    public void setChoiceLabel(String choiceLabel) {
        this.choiceLabel = choiceLabel == null ? null : choiceLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.is_correct_answer
     *
     * @return the value of question_choice.is_correct_answer
     *
     * @mbggenerated
     */
    public Boolean getIsCorrectAnswer() {
        return isCorrectAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.is_correct_answer
     *
     * @param isCorrectAnswer the value for question_choice.is_correct_answer
     *
     * @mbggenerated
     */
    public void setIsCorrectAnswer(Boolean isCorrectAnswer) {
        this.isCorrectAnswer = isCorrectAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.question_id
     *
     * @return the value of question_choice.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.question_id
     *
     * @param questionId the value for question_choice.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_choice.content
     *
     * @return the value of question_choice.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_choice.content
     *
     * @param content the value for question_choice.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}