package testmaker.entity;

public class QuestionUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_user.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_user.reviewer_id
     *
     * @mbggenerated
     */
    private Integer reviewerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_user.question_id
     *
     * @return the value of question_user.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_user.question_id
     *
     * @param questionId the value for question_user.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_user.reviewer_id
     *
     * @return the value of question_user.reviewer_id
     *
     * @mbggenerated
     */
    public Integer getReviewerId() {
        return reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_user.reviewer_id
     *
     * @param reviewerId the value for question_user.reviewer_id
     *
     * @mbggenerated
     */
    public void setReviewerId(Integer reviewerId) {
        this.reviewerId = reviewerId;
    }
}