package testmaker.entity;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.created_on
     *
     * @mbggenerated
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.updated_on
     *
     * @mbggenerated
     */
    private Date updatedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.authoring_finish_date
     *
     * @mbggenerated
     */
    private Date authoringFinishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.authoring_start_date
     *
     * @mbggenerated
     */
    private Date authoringStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.custom_field1
     *
     * @mbggenerated
     */
    private String customField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.custom_field2
     *
     * @mbggenerated
     */
    private String customField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.custom_field3
     *
     * @mbggenerated
     */
    private String customField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.difficulty
     *
     * @mbggenerated
     */
    private Integer difficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.multiple_choice
     *
     * @mbggenerated
     */
    private Boolean multipleChoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.published
     *
     * @mbggenerated
     */
    private Date published;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.reviewing_finish_date
     *
     * @mbggenerated
     */
    private Date reviewingFinishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.reviewing_start_date
     *
     * @mbggenerated
     */
    private Date reviewingStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.score
     *
     * @mbggenerated
     */
    private Short score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.knowledge_point
     *
     * @mbggenerated
     */
    private Integer knowledgePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.language
     *
     * @mbggenerated
     */
    private Integer language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.quality_admin_id
     *
     * @mbggenerated
     */
    private Integer qualityAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.custom_filed1
     *
     * @mbggenerated
     */
    private String customFiled1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.created_on
     *
     * @return the value of question.created_on
     *
     * @mbggenerated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.created_on
     *
     * @param createdOn the value for question.created_on
     *
     * @mbggenerated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.updated_on
     *
     * @return the value of question.updated_on
     *
     * @mbggenerated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.updated_on
     *
     * @param updatedOn the value for question.updated_on
     *
     * @mbggenerated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.authoring_finish_date
     *
     * @return the value of question.authoring_finish_date
     *
     * @mbggenerated
     */
    public Date getAuthoringFinishDate() {
        return authoringFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.authoring_finish_date
     *
     * @param authoringFinishDate the value for question.authoring_finish_date
     *
     * @mbggenerated
     */
    public void setAuthoringFinishDate(Date authoringFinishDate) {
        this.authoringFinishDate = authoringFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.authoring_start_date
     *
     * @return the value of question.authoring_start_date
     *
     * @mbggenerated
     */
    public Date getAuthoringStartDate() {
        return authoringStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.authoring_start_date
     *
     * @param authoringStartDate the value for question.authoring_start_date
     *
     * @mbggenerated
     */
    public void setAuthoringStartDate(Date authoringStartDate) {
        this.authoringStartDate = authoringStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.custom_field1
     *
     * @return the value of question.custom_field1
     *
     * @mbggenerated
     */
    public String getCustomField1() {
        return customField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.custom_field1
     *
     * @param customField1 the value for question.custom_field1
     *
     * @mbggenerated
     */
    public void setCustomField1(String customField1) {
        this.customField1 = customField1 == null ? null : customField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.custom_field2
     *
     * @return the value of question.custom_field2
     *
     * @mbggenerated
     */
    public String getCustomField2() {
        return customField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.custom_field2
     *
     * @param customField2 the value for question.custom_field2
     *
     * @mbggenerated
     */
    public void setCustomField2(String customField2) {
        this.customField2 = customField2 == null ? null : customField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.custom_field3
     *
     * @return the value of question.custom_field3
     *
     * @mbggenerated
     */
    public String getCustomField3() {
        return customField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.custom_field3
     *
     * @param customField3 the value for question.custom_field3
     *
     * @mbggenerated
     */
    public void setCustomField3(String customField3) {
        this.customField3 = customField3 == null ? null : customField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.difficulty
     *
     * @return the value of question.difficulty
     *
     * @mbggenerated
     */
    public Integer getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.difficulty
     *
     * @param difficulty the value for question.difficulty
     *
     * @mbggenerated
     */
    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.memo
     *
     * @return the value of question.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.memo
     *
     * @param memo the value for question.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.multiple_choice
     *
     * @return the value of question.multiple_choice
     *
     * @mbggenerated
     */
    public Boolean getMultipleChoice() {
        return multipleChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.multiple_choice
     *
     * @param multipleChoice the value for question.multiple_choice
     *
     * @mbggenerated
     */
    public void setMultipleChoice(Boolean multipleChoice) {
        this.multipleChoice = multipleChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.published
     *
     * @return the value of question.published
     *
     * @mbggenerated
     */
    public Date getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.published
     *
     * @param published the value for question.published
     *
     * @mbggenerated
     */
    public void setPublished(Date published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.reviewing_finish_date
     *
     * @return the value of question.reviewing_finish_date
     *
     * @mbggenerated
     */
    public Date getReviewingFinishDate() {
        return reviewingFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.reviewing_finish_date
     *
     * @param reviewingFinishDate the value for question.reviewing_finish_date
     *
     * @mbggenerated
     */
    public void setReviewingFinishDate(Date reviewingFinishDate) {
        this.reviewingFinishDate = reviewingFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.reviewing_start_date
     *
     * @return the value of question.reviewing_start_date
     *
     * @mbggenerated
     */
    public Date getReviewingStartDate() {
        return reviewingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.reviewing_start_date
     *
     * @param reviewingStartDate the value for question.reviewing_start_date
     *
     * @mbggenerated
     */
    public void setReviewingStartDate(Date reviewingStartDate) {
        this.reviewingStartDate = reviewingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.score
     *
     * @return the value of question.score
     *
     * @mbggenerated
     */
    public Short getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.score
     *
     * @param score the value for question.score
     *
     * @mbggenerated
     */
    public void setScore(Short score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.author_id
     *
     * @return the value of question.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.author_id
     *
     * @param authorId the value for question.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.knowledge_point
     *
     * @return the value of question.knowledge_point
     *
     * @mbggenerated
     */
    public Integer getKnowledgePoint() {
        return knowledgePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.knowledge_point
     *
     * @param knowledgePoint the value for question.knowledge_point
     *
     * @mbggenerated
     */
    public void setKnowledgePoint(Integer knowledgePoint) {
        this.knowledgePoint = knowledgePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.language
     *
     * @return the value of question.language
     *
     * @mbggenerated
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.language
     *
     * @param language the value for question.language
     *
     * @mbggenerated
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.project_id
     *
     * @return the value of question.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.project_id
     *
     * @param projectId the value for question.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.quality_admin_id
     *
     * @return the value of question.quality_admin_id
     *
     * @mbggenerated
     */
    public Integer getQualityAdminId() {
        return qualityAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.quality_admin_id
     *
     * @param qualityAdminId the value for question.quality_admin_id
     *
     * @mbggenerated
     */
    public void setQualityAdminId(Integer qualityAdminId) {
        this.qualityAdminId = qualityAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type
     *
     * @return the value of question.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type
     *
     * @param type the value for question.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.custom_filed1
     *
     * @return the value of question.custom_filed1
     *
     * @mbggenerated
     */
    public String getCustomFiled1() {
        return customFiled1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.custom_filed1
     *
     * @param customFiled1 the value for question.custom_filed1
     *
     * @mbggenerated
     */
    public void setCustomFiled1(String customFiled1) {
        this.customFiled1 = customFiled1 == null ? null : customFiled1.trim();
    }
}